apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-configmap
data:
  SERVICE_ENDPOINT: <queue_endpoint>
  QUEUE_ID : <queue_ocid>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reader-configmap
data:
  SERVICE_ENDPOINT: <queue_endpoint>
  QUEUE_ID : <queue_ocid>
  SECRET_ID: <secret_ocid>
  HOST: <msql_host>
  USER: <mysql_user>