apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-producer
  template:
    metadata:
      labels:
        app: queue-producer
      annotations:
          instrumentation.opentelemetry.io/inject-python: 'python'
    spec:
      containers:
        - name: queue-producer
          image: pedrochristo/msg_producer:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: producer-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: queue-producer-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: queue-producer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: queue-reader
  template:
    metadata:
      labels:
        app: queue-reader
      annotations:
          instrumentation.opentelemetry.io/inject-python: 'python'
    spec:
      containers:
        - name: queue-reader
          image: pedrochristo/msg_reader:latest
          envFrom:
            - configMapRef:
                name: reader-configmap
